name: Artifactory Snapshot Deployment
on: workflow_dispatch

jobs:
  artifactory-deployment:
    name: Deploy Snapshot to Artifactory
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          server-id: 'snapshots'
          server-username: ARTIFACTORY_USER_ENV_VARIABLE_REFERENCE # puts this in settings.xml ${env.ARTIFACTORY_USER_ENV_REFERENCE}
          server-password: ARTIFACTORY_PASSWORD_ENV_VARIABLE_REFERENCE

      - name: Maven deploy
        run: mvn deploy
        env:
          ARTIFACTORY_USER_ENV_VARIABLE_REFERENCE: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASSWORD_ENV_VARIABLE_REFERENCE: ${{ secrets.ARTIFACTORY_TOKEN }}

